apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  labels:
    app: simple-java-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-java-app

  template:
    metadata:
      labels:
        app: simple-java-app

    spec:
      containers:
      - name: simple-java-app

        image: a7medsayed/simple-java-app:latest

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"